name: Sync Hotfix to Development
on:
  push:
    branches:
      - main
jobs:
  sync:
    if: startsWith(github.ref, 'refs/heads/hotfix/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge hotfix into development
        run: |
          git checkout development
          git merge --no-ff main -m "Merge hotfix from main to development"
          git push origin development
